### ISSUE TITLE
Could not find gibbon-1.2.1 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by mArtinko5MB** [amro/gibbon#158]
Hello friend, 

just installed gibbon 1.2.1 on my server with bundle install

gemfile.rb
```
gem 'gibbon', '~> 1.2'
```

but when i am trying to run it i get
```
Post-install message from gibbon:
IMPORTANT: Gibbon now targets MailChimp API 2.0, which is substantially different from API 1.3.
                             Please use Gibbon 0.4.6 if you need to use API 1.3.
If you're upgrading from <0.5.0 your code WILL break.
Post-install message from seedbank:

  ================================================================================

  Rails 2.x
  ---------
  If you are using Seedbank with Rails 2.x you will need to place the following at 
  the end of your Rakefile so Rubygems can load the seedbank tasks;

    require 'seedbank'
    Seedbank.load_tasks if defined?(Seedbank)

  Rails 3.x and 4.x
  ---------
  Your work here is done!

  ================================================================================
```

my gem list is as follows 

```
$ gem list

*** LOCAL GEMS ***

actionmailer (3.2.13)
actionpack (3.2.13)
activemodel (3.2.13)
activerecord (3.2.13)
activerecord_constraints (0.1.1)
activeresource (3.2.13)
activesupport (3.2.13)
addressable (2.3.8)
after_commit_action (1.0.0)
akami (1.3.1)
apartment (0.20.0)
arel (3.0.3)
bcrypt (3.1.10)
bcrypt-ruby (3.1.5)
bigdecimal (1.2.4)
builder (3.2.2, 3.0.4)
bundler (1.10.5)
carrierwave (0.9.0)
choice (0.1.7)
chronic (0.10.2)
climate_control (0.0.3)
cocaine (0.5.7)
coffee-rails (3.2.2)
coffee-script (2.4.1, 2.2.0)
coffee-script-source (1.9.1.1, 1.6.3)
commonjs (0.2.7)
cookiejar (0.3.2)
counter_culture (0.1.33)
descendants_tracker (0.0.4)
devise (3.0.2)
diff-lcs (1.2.5)
dnsruby (1.58.0)
domain_name (0.5.15)
dropbox-sdk (1.6.3)
em-http-request (1.1.2)
em-socksify (0.3.0)
em-websocket (0.5.1)
email_verifier (0.0.9)
erubis (2.7.0)
eventmachine (1.0.7)
execjs (2.5.2, 2.0.2)
faraday (0.9.2)
fio_api (0.0.4)
foreigner (1.4.2)
gibbon (1.2.1)
git (1.2.9.1)
github_api (0.13.0)
google-analytics-rails (0.0.6)
googlecharts (1.6.8)
gyoku (1.3.1)
hashie (3.4.3)
highline (1.7.8)
hike (1.2.3)
http-cookie (1.0.2)
http_parser.rb (0.6.0)
httparty (0.13.7, 0.13.5)
httpi (2.4.1)
i18n (0.6.1)
io-console (0.4.2)
jeweler (2.0.1)
journey (1.0.4)
jquery-fileupload-rails (0.4.1)
jquery-rails (3.0.4)
js-routes (0.9.9)
json (1.8.3, 1.8.1)
jwt (1.5.2)
less (2.3.3)
less-rails (2.3.3)
libv8 (3.11.8.17 x86_64-linux)
macaddr (1.7.1)
mail (2.5.4)
mechanize (2.7.2)
mime-types (1.25.1)
mini_portile (0.6.2, 0.5.3, 0.5.2)
minitest (4.7.5)
multi_json (1.11.2, 1.11.1, 1.8.2)
multi_xml (0.5.5)
multipart-post (2.0.0)
net-http-digest_auth (1.4)
net-http-persistent (2.9)
nokogiri (1.6.6.4, 1.6.1, 1.6.0)
nori (2.6.0)
ntlm-http (0.1.1)
oauth2 (1.0.0)
orm_adapter (0.5.0)
paperclip (3.5.4)
pg (0.18.2, 0.16.0)
polyglot (0.3.5, 0.3.3)
psych (2.0.5)
rack (1.6.4, 1.5.2, 1.4.7, 1.4.5)
rack-accept (0.4.5)
rack-cache (1.2)
rack-ssl (1.3.4, 1.3.3)
rack-test (0.6.3, 0.6.2)
rails (3.2.13)
rails-erd (1.1.0)
railties (3.2.13)
rake (10.4.2, 10.1.0)
rdoc (4.2.0, 4.1.0, 3.12.2)
ref (1.0.5)
remotipart (1.2.1)
rspec (3.4.0)
rspec-core (3.4.1)
rspec-expectations (3.4.0)
rspec-mocks (3.4.0)
rspec-support (3.4.1)
ruby-graphviz (1.0.9)
rubyzip (1.1.7)
sass (3.4.14)
sass-rails (3.2.6)
savon (2.9.0)
seed_dump (0.4.3)
sprockets (2.2.3, 2.2.2)
sprockets-rails (0.0.1)
systemu (2.6.5)
test-unit (2.1.5.0)
therubyracer (0.11.4)
thor (0.19.1, 0.18.1)
thread_safe (0.3.5)
tilt (1.4.1)
timeliness (0.3.7)
treetop (1.4.15)
turnout (2.1.0)
tzinfo (0.3.44, 0.3.38)
uglifier (2.1.2)
unf (0.1.3)
unf_ext (0.0.6)
unicode (0.4.4)
uuid (2.3.8)
validates_email_format_of (1.5.3)
validates_timeliness (3.0.14)
valvat (0.6.10)
warden (1.2.3)
wasabi (3.3.0)
webrobots (0.1.1)
whenever (0.9.4)
wicked_pdf (0.11.0)
will_paginate (3.0.7)
wkhtmltopdf-binary (0.9.9.3)
```

but after restarting ngix i get 
```
It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:

bundle install
If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:

Is this app supposed to be run as the deploy user?
Is this app being run on the correct Ruby interpreter? Below you will see which Ruby interpreter Phusion Passenger attempted to use.
Please check whether the correct RVM gemset is being used.
Sometimes, RVM gemsets may be broken. Try resetting them.
-------- The exception is as follows: -------

Could not find gibbon-1.2.1 in any of the sources (Bundler::GemNotFound)
  /home/deploy/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.5/lib/bundler/spec_set.rb:92:in `block in materialize'
  /home/deploy/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.5/lib/bundler/spec_set.rb:85:in `map!'
  /home/deploy/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.5/lib/bundler/spec_set.rb:85:in `materialize'
  /home/deploy/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.5/lib/bundler/definition.rb:140:in `specs'
  /home/deploy/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.5/lib/bundler/definition.rb:185:in `specs_for'
  /home/deploy/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.5/lib/bundler/definition.rb:174:in `requested_specs'
  /home/deploy/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.5/lib/bundler/environment.rb:18:in `requested_specs'
  /home/deploy/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.5/lib/bundler/runtime.rb:13:in `setup'
  /home/deploy/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.5/lib/bundler.rb:127:in `setup'
  /home/deploy/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.5/lib/bundler/setup.rb:18:in `<top (required)>'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:406:in `activate_gem'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:288:in `block in run_load_path_setup_code'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:411:in `running_bundler'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:287:in `run_load_path_setup_code'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:99:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:153:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'

```

is this some kind of bug or am i missing something?

Thanks for reply

**Comment by amro** [comment]
Odd. I don't think this is related to Gibbon. Version 1.2.1 is the latest (and last) version of 1.x released.

Is that `gem list` output from your server? Perhaps try `sudo gem install gibbon` manually on the machine in question (or rvmsudo; whatever you're using)?

**Comment by amro** [comment]
A thought: I wonder if your server has two copies of Ruby installed and one is being referenced by your app server and another is in your path.

**Comment by mArtinko5MB** [comment]
I am using one copy of Ruby (i suppose). It's used by my user martin(me) and deploy (there is server set).

But when i type bundle show gibbon as deploy
```
$ bundle show gibbon
/var/lib/gems/2.1.0/gems/gibbon-1.2.0
```

and as a martin
```
$ bundle show gibbon
/var/lib/gems/2.1.0/gems/gibbon-1.2.0
```

is this a problem?

**Comment by mArtinko5MB** [comment]
okay, nevermind ... i think i have resolved it.

i need to install gem on the server first and then it can be used as martin (not the other way around).

Thanks for your time

**Comment by amro** [comment]
Glad you figured it out!
